name: pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - appdirs=1.4.3
  - astor=0.8.0
  - attrs=19.3.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2021.4.13
  - cairo=1.14.12
  - certifi=2020.12.5
  - cffi=1.14.0
  - cfgv=3.2.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.4.1
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.17.2
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distlib=0.3.1
  - easydict=1.9
  - editdistance=0.5.3
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - filelock=3.0.12
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - gast=0.3.3
  - glib=2.63.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - identify=1.5.9
  - idna=2.10
  - imageio=2.8.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - importlib_resources=3.3.0
  - intel-openmp=2020.2
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jasper=2.0.14
  - jedi=0.17.1
  - jinja2=2.11.2
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - jupyterlab=2.1.5
  - jupyterlab_server=1.1.5
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.9.2
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.4
  - nodeenv=1.5.0
  - notebook=6.0.3
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1k
  - packaging=20.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pathspec=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - pixman=0.38.0
  - pre-commit=2.8.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - protobuf=3.11.4
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - readline=8.0
  - regex=2020.6.8
  - requests=2.24.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toml=0.10.1
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.2
  - urllib3=1.25.9
  - virtualenv=20.0.35
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - addict==2.4.0
    - argcomplete==1.12.2
    - astroid==2.4.2
    - atpublic==2.1.1
    - cached-property==1.5.2
    - colorama==0.4.4
    - commonmark==0.9.1
    - configobj==5.0.6
    - dataclasses==0.7
    - dictdiffer==0.8.1
    - diskcache==5.2.1
    - distro==1.5.0
    - dpath==2.0.1
    - dulwich==0.20.21
    - dvc==2.1.0
    - flatten-dict==0.3.0
    - flufl-lock==3.2
    - freetype-py==2.1.0.post1
    - fsspec==0.9.0
    - ftfy==5.8
    - funcy==1.15
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.11
    - grandalf==0.6
    - ipympl==0.5.6
    - isort==5.6.4
    - joblib==0.17.0
    - jsonpath-ng==1.5.2
    - lazy-object-proxy==1.4.3
    - mailchecker==3.3.17
    - mccabe==0.6.1
    - nanotime==0.5.2
    - open3d==0.9.0.0
    - pandas==1.1.4
    - pathlib2==2.3.5
    - phonenumbers==8.12.13
    - ply==3.11
    - plyfile==0.7.2
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pydot==1.4.1
    - pygit2==1.5.0
    - pyglet==1.5.5
    - pygtrie==2.3.2
    - pylint==2.6.0
    - pyopengl==3.1.0
    - pyrender==0.1.43
    - python-benedict==0.22.0
    - python-slugify==4.0.1
    - rich==10.1.0
    - ruamel-yaml==0.16.12
    - ruamel-yaml-clib==0.2.2
    - scikit-learn==0.23.2
    - shortuuid==1.0.1
    - shtab==1.3.6
    - sklearn==0.0
    - smmap==3.0.4
    - tabulate==0.8.7
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - trimesh==3.6.43
    - voluptuous==0.12.0
    - xmltodict==0.12.0
    - yq==2.11.1
    - zc-lockfile==2.0
