colmap:
  dataset_root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense


render_colmap_1:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.016
render_colmap_2:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.01
render_colmap_3:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: None
render_colmap_4:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  ply_file: fused.ply
  voxel_size: 0.014
render_colmap_5:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  ply_file: fused.ply
  voxel_size: 0.0083
render_colmap_6:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  ply_file: fused.ply
  voxel_size: None


dataset_utils_1:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
dataset_utils_2:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
dataset_utils_3:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
dataset_utils_4:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
dataset_utils_5:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
dataset_utils_6:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
