colmap:
  dataset_root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense


render_colmap_1:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.016
render_colmap_2:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.01
render_colmap_3:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: None
render_colmap_4:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  ply_file: fused.ply
  voxel_size: 0.014
render_colmap_5:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  ply_file: fused.ply
  voxel_size: 0.0083
render_colmap_6:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  ply_file: fused.ply
  voxel_size: None
render_colmap_thesis:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis-100_src-fused
  ply_file: fused.ply
  voxel_size: None
render_colmap_thesis_test:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test-100_src-fused
  ply_file: fused.ply
  test_size: 50
  voxel_size: None
render_colmap_thesis_test_squarify:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test_squarify-100_src-fused
  ply_file: fused.ply
  test_size: 50
  squarify: True
  min_size: 1248  # minimal 2**3 and 2**5 divisible number higher than max dimension in the data
  voxel_size: None

render_colmap_7:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.067
render_colmap_8:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.039
render_colmap_9:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-meshed-poisson
  ply_file: meshed-poisson.ply
  voxel_size: 0.027
render_colmap_10:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-fused
  ply_file: fused.ply
  voxel_size: 0.058
render_colmap_11:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-fused
  ply_file: fused.ply
  voxel_size: 0.035
render_colmap_12:
  root: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense
  src_output: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-fused
  ply_file: fused.ply
  voxel_size: 0.024


cpp_render_thesis_splatting:
  type: "COLMAP"
  root_to_process: "/home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test-100_src-fused-splatting"
  ply_path: "/home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/fused.ply"
  max_radius: "0.01"
  renderer_executable: "/home/kremeto1/containers/splatter-app.executable"

cpp_render_thesis_spheres:
  type: "COLMAP"
  root_to_process: "/home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test-100_src-fused-spheres"
  ply_path: "/home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/fused.ply"
  max_radius: "0.01"
  renderer_executable: "/home/kremeto1/containers/renderer-app.executable"


inloc_cutouts_thesis_test_squarify:
  input_root: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test_squarify-100_src-fused
  input_ply_path: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/fused.ply
  input_root_colmap: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/sparse
  output_root: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_thesis_test_squarify-100_src-fused_inloc_format
  test_size: "50"
  squarify: "True"

inloc_cutouts_thesis_test:
  input_root: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test-100_src-fused
  input_ply_path: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/fused.ply
  input_root_colmap: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/sparse
  output_root: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_thesis_test-100_src-fused_inloc_format
  test_size: "50"
  squarify: "False"

inloc_cutouts_thesis_splatting_squarify:
  input_root: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test-100_src-fused-splatting
  input_ply_path: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/fused.ply
  input_root_colmap: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/sparse
  output_root: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_thesis_splatting_squarify-100_src-fused_inloc_format
  test_size: "50"
  squarify: "True"

inloc_cutouts_thesis_spheres_squarify:
  input_root: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_thesis_test-100_src-fused-spheres
  input_ply_path: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/fused.ply
  input_root_colmap: /home/kremeto1/neural_rendering/datasets/processed/imc/grand_place_brussels/dense/dense/sparse
  output_root: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_thesis_spheres_squarify-100_src-fused_inloc_format
  test_size: "50"
  squarify: "True"


dataset_utils_1:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
dataset_utils_2:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
dataset_utils_3:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
dataset_utils_4:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
dataset_utils_5:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
dataset_utils_6:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused

dataset_utils_7:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-meshed-poisson
dataset_utils_8:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-meshed-poisson
dataset_utils_9:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-meshed-poisson
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-meshed-poisson
dataset_utils_10:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-1_src-fused
dataset_utils_11:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-5_src-fused
dataset_utils_12:
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/post_processed/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-fused
  output_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-10_src-fused


train_nriw_1:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  fixed_total_kimg: 400
  finetune_total_kimg: 100
train_nriw_2:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  fixed_total_kimg: 400
  finetune_total_kimg: 100
train_nriw_3:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  fixed_total_kimg: 400
  finetune_total_kimg: 100
train_nriw_4:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  fixed_total_kimg: 400
  finetune_total_kimg: 100
train_nriw_5:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  fixed_total_kimg: 400
  finetune_total_kimg: 100
train_nriw_6:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  fixed_total_kimg: 400
  finetune_total_kimg: 100


evaluate_nriw_1:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
  timestamp: 2020-12-26-19-31-08
evaluate_nriw_2:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
  timestamp: 2021-01-05-23-23-07
evaluate_nriw_3:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
  timestamp: 2020-12-19-18-28-56
evaluate_nriw_4:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
  timestamp: 2021-01-05-23-23-46
evaluate_nriw_5:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
  timestamp: 2021-01-06-05-27-51
evaluate_nriw_6:
  model_parent_dir: /home/kremeto1/neural_rendering/models/grand_place_brussels/
  dataset_name: grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  dataset_parent_dir: /home/kremeto1/neural_rendering/datasets/final/imc/grand_place_brussels_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
  timestamp: 2020-12-19-00-07-25
