stages:
  matlab_preprocessing:
    cmd: bash -lc "sbatch --wait ../scripts/artwin_matlab_preprocess.sh preprocess"
    deps:
    - ../../artwin/preprocess.m
    - ../scripts/artwin_matlab_preprocess.sh
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29:
        cache: false
        persist: true
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53:
        cache: false
        persist: true

  matlab_preprocessing2:
    cmd: bash -lc "sbatch --wait ../scripts/artwin_matlab_preprocess.sh preprocess_v2"
    deps:
    - ../../artwin/preprocess.m
    - ../scripts/artwin_matlab_preprocess.sh
    outs:
    - /nfs/projects/artwin/experiments/matlab_60_fov:
        cache: false
        persist: true


  render_colmap_1:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 1"
    deps:
    - ../../colmap/load_data.py
    - ../scripts/render_colmap.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29
    params:
    - render_colmap_1.voxel_size
    - render_colmap_1.ply_file
    - render_colmap_1.root
    - render_colmap_1.src_output
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29-rendered:
        cache: false
        persist: true

  render_colmap_2:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 2"
    deps:
    - ../../colmap/load_data.py
    - ../scripts/render_colmap.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53
    params:
    - render_colmap_2.voxel_size
    - render_colmap_2.ply_file
    - render_colmap_2.root
    - render_colmap_2.src_output
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53-rendered:
        cache: false
        persist: true

  render_colmap_3:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 3"
    deps:
    - ../../colmap/load_data.py
    - ../scripts/render_colmap.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29
    params:
    - render_colmap_3.voxel_size
    - render_colmap_3.ply_file
    - render_colmap_3.root
    - render_colmap_3.src_output
    - render_colmap_3.bg_color
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29-rendered-black_bg:
        cache: false
        persist: true

  render_colmap_4:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 4"
    deps:
    - ../../colmap/load_data.py
    - ../scripts/render_colmap.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53
    params:
    - render_colmap_4.voxel_size
    - render_colmap_4.ply_file
    - render_colmap_4.root
    - render_colmap_4.src_output
    - render_colmap_4.bg_color
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53-rendered-black_bg:
        cache: false
        persist: true

  render_colmap_5:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 5"
    deps:
    - ../../colmap/load_data.py
    - ../scripts/render_colmap.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29
    params:
    - render_colmap_5.voxel_size
    - render_colmap_5.ply_file
    - render_colmap_5.root
    - render_colmap_5.src_output
    - render_colmap_5.bg_color
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29-rendered-mesh-black_bg:
        cache: false
        persist: true

  render_colmap_6:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 6"
    deps:
    - ../../colmap/load_data.py
    - ../scripts/render_colmap.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53
    params:
    - render_colmap_6.voxel_size
    - render_colmap_6.ply_file
    - render_colmap_6.root
    - render_colmap_6.src_output
    - render_colmap_6.bg_color
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53-rendered-mesh-black_bg:
        cache: false
        persist: true

  join_datasets:
    cmd: ~/.conda/envs/pipeline/bin/python ../../artwin/join_datasets.py "/nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender" "2019-*-rendered"
    deps:
    - ../../artwin/join_datasets.py
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_08.31.29-rendered
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/2019-09-28_16.11.53-rendered
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/joined_dataset:
        cache: false
        persist: true


  dataset_utils_1:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 1"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/joined_dataset
    params:
    - dataset_utils_1.dataset_name
    - dataset_utils_1.dataset_parent_dir
    - dataset_utils_1.output_dir
    outs:
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/joined_dataset_tfrecord:
        cache: false
        persist: true


  dataset_utils_2:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 2"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - /nfs/projects/artwin/experiments/matlab_60_fov
    params:
    - dataset_utils_1.dataset_name
    - dataset_utils_1.dataset_parent_dir
    - dataset_utils_1.output_dir
    outs:
    - /nfs/projects/artwin/experiments/matlab_60_fov-joined_dataset_tfrecord:
        cache: false
        persist: true


  train_nriw_1:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 1"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../scripts/train_nriw.sh
    - /nfs/projects/artwin/experiments/as_colmap_60_fov_pyrender/joined_dataset_tfrecord
    params:
    - train_nriw_1.dataset_name
    - train_nriw_1.dataset_parent_dir
    - train_nriw_1.model_parent_dir


  train_nriw_2:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 2"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../scripts/train_nriw.sh
    - /nfs/projects/artwin/experiments/matlab_60_fov-joined_dataset_tfrecord
    params:
    - train_nriw_2.dataset_name
    - train_nriw_2.dataset_parent_dir
    - train_nriw_2.model_parent_dir

  train_nriw_3:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw_wo_pretrain.sh 3"
    deps:
    - ../../neural_rerendering.py
    - ../scripts/train_nriw_wo_pretrain.sh
    - /nfs/projects/artwin/experiments/matlab_60_fov-joined_dataset_tfrecord
    params:
    - train_nriw_3.dataset_name
    - train_nriw_3.dataset_parent_dir
    - train_nriw_3.model_parent_dir

  evaluate_nriw_1:
      cmd: bash -lc "sbatch --wait ../scripts/evaluate_nriw.sh 1"
      deps:
      - ../../neural_rerendering.py
      - ../../evaluate_quantitative_metrics.py
      - /nfs/projects/artwin/experiments/matlab_60_fov-modelartwin_matlab-2021-03-20-21-06-40-finetune_appearance
      params:
      - evaluate_nriw_1.model_parent_dir
      - evaluate_nriw_1.dataset_name
      - evaluate_nriw_1.dataset_parent_dir
      - evaluate_nriw_1.timestamp

  evaluate_nriw:
    foreach: [1, 2]
    do:
      cmd: >-
        bash -lc "sbatch --wait ../scripts/evaluate_nriw.sh ${item}"
      deps:
      - ../../neural_rerendering.py
      - ../../evaluate_quantitative_metrics.py
      - ../scripts/evaluate_nriw.sh
      params:
      - evaluate_nriw_${item}.model_parent_dir
      - evaluate_nriw_${item}.dataset_name
      - evaluate_nriw_${item}.dataset_parent_dir
      - evaluate_nriw_${item}.timestamp
