stages:
  render_colmap_1:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 1"
    deps:
    - ../../colmap/load_data.py
    - ../../datasets/processed/imc/hagia_sophia_interior
    - ../scripts/render_colmap.sh
    params:
    - render_colmap_1.downsample
    - render_colmap_1.ply_file
    - render_colmap_1.root
    - render_colmap_1.src_output
    outs:
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson:
        cache: false
        persist: true
  render_colmap_2:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 2"
    deps:
    - ../../colmap/load_data.py
    - ../../datasets/processed/imc/hagia_sophia_interior
    - ../scripts/render_colmap.sh
    params:
    - render_colmap_2.downsample
    - render_colmap_2.ply_file
    - render_colmap_2.root
    - render_colmap_2.src_output
    outs:
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson:
        cache: false
        persist: true
  render_colmap_3:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 3"
    deps:
    - ../../colmap/load_data.py
    - ../../datasets/processed/imc/hagia_sophia_interior
    - ../scripts/render_colmap.sh
    params:
    - render_colmap_3.downsample
    - render_colmap_3.ply_file
    - render_colmap_3.root
    - render_colmap_3.src_output
    outs:
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson:
        cache: false
        persist: true
  render_colmap_4:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 4"
    deps:
    - ../../colmap/load_data.py
    - ../../datasets/processed/imc/hagia_sophia_interior
    - ../scripts/render_colmap.sh
    params:
    - render_colmap_4.downsample
    - render_colmap_4.ply_file
    - render_colmap_4.root
    - render_colmap_4.src_output
    outs:
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-fused:
        cache: false
        persist: true
  render_colmap_5:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 5"
    deps:
    - ../../colmap/load_data.py
    - ../../datasets/processed/imc/hagia_sophia_interior
    - ../scripts/render_colmap.sh
    params:
    - render_colmap_5.downsample
    - render_colmap_5.ply_file
    - render_colmap_5.root
    - render_colmap_5.src_output
    outs:
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-fused:
        cache: false
        persist: true
  render_colmap_6:
    cmd: bash -lc "sbatch --wait ../scripts/render_colmap.sh 6"
    deps:
    - ../../colmap/load_data.py
    - ../../datasets/processed/imc/hagia_sophia_interior
    - ../scripts/render_colmap.sh
    params:
    - render_colmap_6.downsample
    - render_colmap_6.ply_file
    - render_colmap_6.root
    - render_colmap_6.src_output
    outs:
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-fused:
        cache: false
        persist: true


  dataset_utils_1:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 1"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
    params:
    - dataset_utils_1.dataset_name
    - dataset_utils_1.dataset_parent_dir
    - dataset_utils_1.output_dir
    outs:
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson:
        cache: false
        persist: true
  dataset_utils_2:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 2"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
    params:
    - dataset_utils_2.dataset_name
    - dataset_utils_2.dataset_parent_dir
    - dataset_utils_2.output_dir
    outs:
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson:
        cache: false
        persist: true
  dataset_utils_3:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 3"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
    params:
    - dataset_utils_3.dataset_name
    - dataset_utils_3.dataset_parent_dir
    - dataset_utils_3.output_dir
    outs:
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson:
        cache: false
        persist: true
  dataset_utils_4:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 4"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
    params:
    - dataset_utils_4.dataset_name
    - dataset_utils_4.dataset_parent_dir
    - dataset_utils_4.output_dir
    outs:
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-fused:
        cache: false
        persist: true
  dataset_utils_5:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 5"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
    params:
    - dataset_utils_5.dataset_name
    - dataset_utils_5.dataset_parent_dir
    - dataset_utils_5.output_dir
    outs:
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-fused:
        cache: false
        persist: true
  dataset_utils_6:
    cmd: bash -lc "sbatch --wait ../scripts/run_dataset_utils.sh 6"
    deps:
    - ../../dataset_utils.py
    - ../scripts/run_dataset_utils.sh
    - ../../datasets/post_processed/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
    params:
    - dataset_utils_6.dataset_name
    - dataset_utils_6.dataset_parent_dir
    - dataset_utils_6.output_dir
    outs:
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-fused:
        cache: false
        persist: true


  train_nriw_1:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 1"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../scripts/train_nriw.sh
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-meshed-poisson
    params:
    - train_nriw_1.dataset_name
    - train_nriw_1.dataset_parent_dir
    - train_nriw_1.model_parent_dir
  train_nriw_2:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 2"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-meshed-poisson
    params:
    - train_nriw_2.dataset_name
    - train_nriw_2.dataset_parent_dir
    - train_nriw_2.model_parent_dir
  train_nriw_3:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 3"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-meshed-poisson
    params:
    - train_nriw_3.dataset_name
    - train_nriw_3.dataset_parent_dir
    - train_nriw_3.model_parent_dir
  train_nriw_4:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 4"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-25_src-fused
    params:
    - train_nriw_4.dataset_name
    - train_nriw_4.dataset_parent_dir
    - train_nriw_4.model_parent_dir
  train_nriw_5:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 5"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-50_src-fused
    params:
    - train_nriw_5.dataset_name
    - train_nriw_5.dataset_parent_dir
    - train_nriw_5.model_parent_dir
  train_nriw_6:
    cmd: bash -lc "sbatch --wait ../scripts/train_nriw.sh 6"
    deps:
    - ../../pretrain_appearance.py
    - ../../neural_rerendering.py
    - ../../datasets/final/imc/hagia_sophia_interior_minsz-512_valr-0.2_pts-2.0_down-100_src-fused
    params:
    - train_nriw_6.dataset_name
    - train_nriw_6.dataset_parent_dir
    - train_nriw_6.model_parent_dir
