render_inloc_1:
  n_max_per_scan: "4000000"
  point_size: "2.0"
  bg_color: "0.0,0.0,0.0"

dataset_utils_1:
  dataset_name: "inloc"
  dataset_parent_dir: "/home/kremeto1/neural_rendering/datasets/post_processed/inloc/inloc_rendered_1"
  output_dir: "/home/kremeto1/neural_rendering/datasets/final/inloc/inloc_rendered_1"

render_inloc_query_1:
  output_path: "/home/kremeto1/neural_rendering/datasets/post_processed/inloc/query_rendered_1"
  mat_path: "/home/kremeto1/bdechamps_inloc/outputs/densePE_top100_shortlist.mat"
  max_img_size: 4032

render_inloc_query_2:
  output_path: "/home/kremeto1/neural_rendering/datasets/post_processed/inloc/query_rendered_2"
  mat_path: "/home/kremeto1/bdechamps_inloc/outputs/densePE_top100_shortlist.mat"
  max_img_size: 512

dataset_utils_subfolders_3:
  input_dir: "/home/kremeto1/neural_rendering/datasets/post_processed/inloc/query_512_borders"
  output_dir: "/home/kremeto1/neural_rendering/datasets/final/inloc/query_512_borders"

infer_nriw_on_subfolders_1:
  input_dir: "/home/kremeto1/neural_rendering/datasets/post_processed/inloc/query_512_borders"
  output_dir: "/home/kremeto1/neural_rendering/inferences/inloc/query_512_borders"
  trained_model_dir: "/home/bdechamps/neural_rerendering_in_the_wild/train_models/inloc_db-staged-finetune_appearance"
